

// Rest Client Extenstion
# This extension sometimes cause error so don't be dependent on it. Use Postman. if this make unexpected error 


# POST http://localhost:8000/signup
# Content-Type: "application/json"

# {
#     "fullname":"Ansari Danish",
#     "email": "kjfksdjfk@somethig.com", 
#     "password": "Indian@123"
# }

# POST http://localhost:8000/signin
# Content-Type: "application/json"

# {
#     "email": "dan72mail@gmail.com", 
#     "password": "Indian@123"
# }

# GET http://localhost:8000/get-upload-url



# POST http://localhost:8000/create-blog
# Content-Type: "application/json"
# Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTg4Y2IyMDAxM2QwOGRlNzUyMzNlOSIsImlhdCI6MTcwOTczOTE4Nn0.XsmrVojAlmf7G97p7PRYAwgdMoUtAcXDZ_L90FFMwDA"

# {
#     "blog-name":"this is blog",
# }

# GET http://localhost:8000/latest-blogs

# GET http://localhost:8000/trending-blogs


# POST http://localhost:8000/search-blogs
# Content-Type: "application/json"

# {
#     "tag": "aws"
# }
POST http://localhost:8000/search-users
Content-Type: "application/json"

{
    "query": "vishal"
}
